networks:
  linto:
    external: true
  net_stt_services:
    external: true
  task_broker_services:
    external: true
services:
  stt-french-whisper-v3:
    deploy:
      labels:
        - linto.gateway.enable=true
        - linto.gateway.port=80
        - 'linto.gateway.desc={"en": "LinTO French- Whisper Transcription Service", "fr": "LinTO Français- Service de transcription Whisper"}'
        - linto.gateway.scope=cm,api,stt
        - linto.gateway.endpoints=/stt-french-whisper-v3,
        - linto.gateway.endpoint.stt-french-whisper-v3.middlewares=logs
        - linto.gateway.endpoint.stt-french-whisper-v3.middlewares.logs.debug=*
      mode: replicated
      replicas: 1
    environment:
      ACCOUSTIC: 1
      BROKER_PASS: $REDIS_PASSWORD
      CONCURRENCY: "1"
      DIARIZATION_DEFAULT: "false"
      KEEP_AUDIO: 0
      LANGUAGE: fr-FR
      MODEL_QUALITY: 1
      MODEL_TYPE: whisper
      MONGO_HOST: stt-mongo
      MONGO_PORT: 27017
      RESOLVE_POLICY: ANY
      RESSOURCE_FOLDER: /home/dam/shared_mount
      SERVICES_BROKER: redis://task-broker-redis:6379
      SERVICE_NAME: stt-french-whisper-v3
    healthcheck:
      interval: 15s
      retries: 4
      start_period: 10s
      timeout: 10s
    image: lintoai/linto-platform-transcription-service:latest-unstable
    networks:
      - net_stt_services
      - task_broker_services
    volumes:
      - /home/dam/shared_mount/audios/api_uploads/:/opt/audio
  stt-french-whisper-v3_workers:
    command: []
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      BROKER_PASS: $REDIS_PASSWORD
      CONCURRENCY: "1"
      DEVICE: cuda
      LANGUAGE: fr-FR
      MODEL: large-v3
      MODEL_TYPE: whisper
      SERVICES_BROKER: redis://task-broker-redis:6379
      SERVICE_MODE: task
      SERVICE_NAME: stt-french-whisper-v3
      NVIDIA_VISIBLE_DEVICES: 0
      NVIDIA_DRIVER_CAPABILITIES: all
    image: lintoai/linto-stt-whisper:latest-unstable
    networks:
      - net_stt_services
      - task_broker_services
    volumes:
      - /home/dam/shared_mount/audios/api_uploads/:/opt/audio
      - /home/dam/shared_mount/models/:/root/.cache
version: "3.7"
