networks:
  linto:
    external: true
services:
  studio-frontend:
    command:
      - --build
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.studio-frontend-router.entrypoints=websecure
        - traefik.http.routers.studio-frontend-router.rule=Host(`localhost`) && PathPrefix(`/`)
        - traefik.http.routers.studio-frontend-router.tls=true
        - traefik.http.services.studio-frontend-service.loadbalancer.server.port=80
      mode: replicated
      replicas: 1
    environment:
      VUE_APP_CONVO_API: /cm-api/api
      VUE_APP_CONVO_AUTH: /cm-api/auth
      VUE_APP_DISABLE_USER_CREATION: "false"
      VUE_APP_EXPERIMENTAL_HIGHLIGHT: "false"
      VUE_APP_MAX_CARACTERS_PER_PAGE: 20000
      VUE_APP_NAME: LinTO studio
      VUE_APP_PUBLIC_MEDIA: /cm-api/media
      VUE_APP_SESSION_WS: https://localhost
      VUE_APP_SESSION_WS_PATH: /cm-api/socket.io
      VUE_APP_TURN_PER_PAGE: 10
      VUE_APP_TURN_SIZE: 2000
      VUE_APP_WEBSOCKET_PATH: /ws/socket.io
      VUE_APP_WEBSOCKET_SERVER: wss://localhost
    image: lintoai/studio-frontend:latest-unstable
    networks:
      - linto
version: "3.7"
