networks:
  linto:
    external: true
  net_studio:
    external: true
  session_network:
    external: true
services:
  studio-api:
    command:
      - --run-cmd=node app.js
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.studio-api-router.entrypoints=websecure
        - traefik.http.routers.studio-api-router.rule=Host(`localhost`) && PathPrefix(`/cm-api`)
        - traefik.http.routers.studio-api-router.tls=true
        - traefik.http.services.studio-api-service.loadbalancer.server.port=80
        - traefik.http.middlewares.studio-api-stripprefix.stripPrefix.prefixes=/cm-api
        - traefik.http.routers.studio-api-router.middlewares=studio-api-stripprefix@docker
      mode: replicated
      replicas: 1
    environment:
      AXIOS_SIZE_FILE_MAX: "1000000000"
      CM_JWT_SECRET: jwt_secret
      CM_REFRESH_SECRET: jwt_refresh_secret
      COMPONENTS: WebServer,MongoMigration
      CORS_API_WHITELIST: https://localhost
      CORS_ENABLED: "true"
      DB_HOST: studio_mongodb
      DB_MIGRATION_TARGET: 1.5.0
      DB_NAME: conversations
      DB_PORT: "27017"
      DB_REQUIRE_LOGIN: "false"
      DISABLE_USER_CREATION: "false"
      EXPORT_TEMPLATE: ""
      EXPRESS_SIZE_FILE_MAX: 1gb
      GATEWAY_SERVICES: http://api-gateway
      LLM_GATEWAY_SERVICES: http://llm-gateway/
      MAX_SUBTITLE_VERSION: 5
      NO_REPLY_EMAIL: ""
      SESSION_API_ENDPOINT: http://session-api/v1
      SMTP_AUTH: ""
      SMTP_HOST: ""
      SMTP_PORT: ""
      SMTP_PSWD: ""
      SMTP_REQUIRE_TLS: ""
      SMTP_SECURE: ""
      WEBSERVER_HTTP_PORT: 80
    image: lintoai/studio-api:latest-unstable
    networks:
      - net_studio
      - session_network
      - linto
    volumes:
      - /home/dam/shared_mount/conversation-manager/:/usr/src/app/conversation-manager/storages/
  studio_mongodb:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role==manager
      replicas: 1
    image: mongo:6.0.2
    networks:
      - net_studio
    volumes:
      - /home/dam/deployment_config/database/db-cm-data:/data/db
version: "3.7"
