networks:
  linto:
    external: true
services:
  traefik:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.ip==ingress
          - node.role==manager
      replicas: 1
    image: traefik:2.9.1
    networks:
      - linto
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/dam/shared_mount/traefik/traefik.toml:/traefik.toml:ro
      - /home/dam/shared_mount/traefik/dynamic.toml:/dynamic.toml
      - /home/dam/shared_mount/certs/acme.json:/acme.json
      - /home/dam/shared_mount/certs-mkcert:/certs
      - /home/dam/deployment_config/traefik/logs:/var/log/traefik
version: "3.7"
